{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    "energy = pd.read_csv(\"csv_files/global_energy_consumption.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Country</th>\n",
       "      <th>Year</th>\n",
       "      <th>Total Energy Consumption (TWh)</th>\n",
       "      <th>Per Capita Energy Use (kWh)</th>\n",
       "      <th>Renewable Energy Share (%)</th>\n",
       "      <th>Fossil Fuel Dependency (%)</th>\n",
       "      <th>Industrial Energy Use (%)</th>\n",
       "      <th>Household Energy Use (%)</th>\n",
       "      <th>Carbon Emissions (Million Tons)</th>\n",
       "      <th>Energy Price Index (USD/kWh)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Canada</td>\n",
       "      <td>2018</td>\n",
       "      <td>9525.38</td>\n",
       "      <td>42301.43</td>\n",
       "      <td>13.70</td>\n",
       "      <td>70.47</td>\n",
       "      <td>45.18</td>\n",
       "      <td>19.96</td>\n",
       "      <td>3766.11</td>\n",
       "      <td>0.12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>UK</td>\n",
       "      <td>2016</td>\n",
       "      <td>4682.02</td>\n",
       "      <td>2491.92</td>\n",
       "      <td>40.47</td>\n",
       "      <td>69.06</td>\n",
       "      <td>20.07</td>\n",
       "      <td>23.39</td>\n",
       "      <td>2242.11</td>\n",
       "      <td>0.35</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Russia</td>\n",
       "      <td>2019</td>\n",
       "      <td>6762.79</td>\n",
       "      <td>11886.43</td>\n",
       "      <td>6.05</td>\n",
       "      <td>18.66</td>\n",
       "      <td>54.40</td>\n",
       "      <td>34.34</td>\n",
       "      <td>4728.25</td>\n",
       "      <td>0.47</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>Germany</td>\n",
       "      <td>2017</td>\n",
       "      <td>3110.30</td>\n",
       "      <td>47370.83</td>\n",
       "      <td>78.07</td>\n",
       "      <td>21.22</td>\n",
       "      <td>52.92</td>\n",
       "      <td>10.38</td>\n",
       "      <td>4878.06</td>\n",
       "      <td>0.18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>Canada</td>\n",
       "      <td>2015</td>\n",
       "      <td>5090.34</td>\n",
       "      <td>13938.48</td>\n",
       "      <td>24.49</td>\n",
       "      <td>30.24</td>\n",
       "      <td>27.68</td>\n",
       "      <td>30.35</td>\n",
       "      <td>880.75</td>\n",
       "      <td>0.13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9982</th>\n",
       "      <td>Australia</td>\n",
       "      <td>2015</td>\n",
       "      <td>7726.33</td>\n",
       "      <td>20916.66</td>\n",
       "      <td>77.08</td>\n",
       "      <td>31.40</td>\n",
       "      <td>21.40</td>\n",
       "      <td>28.64</td>\n",
       "      <td>3281.04</td>\n",
       "      <td>0.40</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9984</th>\n",
       "      <td>Australia</td>\n",
       "      <td>2017</td>\n",
       "      <td>6734.71</td>\n",
       "      <td>37318.32</td>\n",
       "      <td>18.42</td>\n",
       "      <td>17.28</td>\n",
       "      <td>53.41</td>\n",
       "      <td>14.53</td>\n",
       "      <td>3381.32</td>\n",
       "      <td>0.15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9989</th>\n",
       "      <td>Germany</td>\n",
       "      <td>2018</td>\n",
       "      <td>5807.70</td>\n",
       "      <td>12065.14</td>\n",
       "      <td>28.26</td>\n",
       "      <td>59.66</td>\n",
       "      <td>43.11</td>\n",
       "      <td>26.66</td>\n",
       "      <td>1087.96</td>\n",
       "      <td>0.38</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9995</th>\n",
       "      <td>Canada</td>\n",
       "      <td>2017</td>\n",
       "      <td>9786.50</td>\n",
       "      <td>30481.07</td>\n",
       "      <td>14.87</td>\n",
       "      <td>70.25</td>\n",
       "      <td>53.93</td>\n",
       "      <td>19.94</td>\n",
       "      <td>620.85</td>\n",
       "      <td>0.29</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9999</th>\n",
       "      <td>Brazil</td>\n",
       "      <td>2018</td>\n",
       "      <td>5387.71</td>\n",
       "      <td>17454.75</td>\n",
       "      <td>89.62</td>\n",
       "      <td>49.97</td>\n",
       "      <td>30.04</td>\n",
       "      <td>37.96</td>\n",
       "      <td>4606.33</td>\n",
       "      <td>0.11</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2088 rows × 10 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        Country  Year  Total Energy Consumption (TWh)  \\\n",
       "0        Canada  2018                         9525.38   \n",
       "5            UK  2016                         4682.02   \n",
       "17       Russia  2019                         6762.79   \n",
       "29      Germany  2017                         3110.30   \n",
       "34       Canada  2015                         5090.34   \n",
       "...         ...   ...                             ...   \n",
       "9982  Australia  2015                         7726.33   \n",
       "9984  Australia  2017                         6734.71   \n",
       "9989    Germany  2018                         5807.70   \n",
       "9995     Canada  2017                         9786.50   \n",
       "9999     Brazil  2018                         5387.71   \n",
       "\n",
       "      Per Capita Energy Use (kWh)  Renewable Energy Share (%)  \\\n",
       "0                        42301.43                       13.70   \n",
       "5                         2491.92                       40.47   \n",
       "17                       11886.43                        6.05   \n",
       "29                       47370.83                       78.07   \n",
       "34                       13938.48                       24.49   \n",
       "...                           ...                         ...   \n",
       "9982                     20916.66                       77.08   \n",
       "9984                     37318.32                       18.42   \n",
       "9989                     12065.14                       28.26   \n",
       "9995                     30481.07                       14.87   \n",
       "9999                     17454.75                       89.62   \n",
       "\n",
       "      Fossil Fuel Dependency (%)  Industrial Energy Use (%)  \\\n",
       "0                          70.47                      45.18   \n",
       "5                          69.06                      20.07   \n",
       "17                         18.66                      54.40   \n",
       "29                         21.22                      52.92   \n",
       "34                         30.24                      27.68   \n",
       "...                          ...                        ...   \n",
       "9982                       31.40                      21.40   \n",
       "9984                       17.28                      53.41   \n",
       "9989                       59.66                      43.11   \n",
       "9995                       70.25                      53.93   \n",
       "9999                       49.97                      30.04   \n",
       "\n",
       "      Household Energy Use (%)  Carbon Emissions (Million Tons)  \\\n",
       "0                        19.96                          3766.11   \n",
       "5                        23.39                          2242.11   \n",
       "17                       34.34                          4728.25   \n",
       "29                       10.38                          4878.06   \n",
       "34                       30.35                           880.75   \n",
       "...                        ...                              ...   \n",
       "9982                     28.64                          3281.04   \n",
       "9984                     14.53                          3381.32   \n",
       "9989                     26.66                          1087.96   \n",
       "9995                     19.94                           620.85   \n",
       "9999                     37.96                          4606.33   \n",
       "\n",
       "      Energy Price Index (USD/kWh)  \n",
       "0                             0.12  \n",
       "5                             0.35  \n",
       "17                            0.47  \n",
       "29                            0.18  \n",
       "34                            0.13  \n",
       "...                            ...  \n",
       "9982                          0.40  \n",
       "9984                          0.15  \n",
       "9989                          0.38  \n",
       "9995                          0.29  \n",
       "9999                          0.11  \n",
       "\n",
       "[2088 rows x 10 columns]"
      ]
     },
     "execution_count": 49,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Delete rows that are not in the range of 2015-2019\n",
    "energy = energy[(energy[\"Year\"] >= 2015) & (energy[\"Year\"]<= 2019)]\n",
    "energy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "metadata": {},
   "outputs": [],
   "source": [
    "energy.columns = energy.columns.str.lower().str.replace(' ', '_')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>country</th>\n",
       "      <th>year</th>\n",
       "      <th>total_energy_consumption_(twh)</th>\n",
       "      <th>per_capita_energy_use_(kwh)</th>\n",
       "      <th>renewable_energy_share_(%)</th>\n",
       "      <th>fossil_fuel_dependency_(%)</th>\n",
       "      <th>industrial_energy_use_(%)</th>\n",
       "      <th>household_energy_use_(%)</th>\n",
       "      <th>carbon_emissions_(million_tons)</th>\n",
       "      <th>energy_price_index_(usd/kwh)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Canada</td>\n",
       "      <td>2018</td>\n",
       "      <td>9525.38</td>\n",
       "      <td>42301.43</td>\n",
       "      <td>13.70</td>\n",
       "      <td>70.47</td>\n",
       "      <td>45.18</td>\n",
       "      <td>19.96</td>\n",
       "      <td>3766.11</td>\n",
       "      <td>0.12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>UK</td>\n",
       "      <td>2016</td>\n",
       "      <td>4682.02</td>\n",
       "      <td>2491.92</td>\n",
       "      <td>40.47</td>\n",
       "      <td>69.06</td>\n",
       "      <td>20.07</td>\n",
       "      <td>23.39</td>\n",
       "      <td>2242.11</td>\n",
       "      <td>0.35</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Russia</td>\n",
       "      <td>2019</td>\n",
       "      <td>6762.79</td>\n",
       "      <td>11886.43</td>\n",
       "      <td>6.05</td>\n",
       "      <td>18.66</td>\n",
       "      <td>54.40</td>\n",
       "      <td>34.34</td>\n",
       "      <td>4728.25</td>\n",
       "      <td>0.47</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>Germany</td>\n",
       "      <td>2017</td>\n",
       "      <td>3110.30</td>\n",
       "      <td>47370.83</td>\n",
       "      <td>78.07</td>\n",
       "      <td>21.22</td>\n",
       "      <td>52.92</td>\n",
       "      <td>10.38</td>\n",
       "      <td>4878.06</td>\n",
       "      <td>0.18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>Canada</td>\n",
       "      <td>2015</td>\n",
       "      <td>5090.34</td>\n",
       "      <td>13938.48</td>\n",
       "      <td>24.49</td>\n",
       "      <td>30.24</td>\n",
       "      <td>27.68</td>\n",
       "      <td>30.35</td>\n",
       "      <td>880.75</td>\n",
       "      <td>0.13</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    country  year  total_energy_consumption_(twh)  \\\n",
       "0    Canada  2018                         9525.38   \n",
       "5        UK  2016                         4682.02   \n",
       "17   Russia  2019                         6762.79   \n",
       "29  Germany  2017                         3110.30   \n",
       "34   Canada  2015                         5090.34   \n",
       "\n",
       "    per_capita_energy_use_(kwh)  renewable_energy_share_(%)  \\\n",
       "0                      42301.43                       13.70   \n",
       "5                       2491.92                       40.47   \n",
       "17                     11886.43                        6.05   \n",
       "29                     47370.83                       78.07   \n",
       "34                     13938.48                       24.49   \n",
       "\n",
       "    fossil_fuel_dependency_(%)  industrial_energy_use_(%)  \\\n",
       "0                        70.47                      45.18   \n",
       "5                        69.06                      20.07   \n",
       "17                       18.66                      54.40   \n",
       "29                       21.22                      52.92   \n",
       "34                       30.24                      27.68   \n",
       "\n",
       "    household_energy_use_(%)  carbon_emissions_(million_tons)  \\\n",
       "0                      19.96                          3766.11   \n",
       "5                      23.39                          2242.11   \n",
       "17                     34.34                          4728.25   \n",
       "29                     10.38                          4878.06   \n",
       "34                     30.35                           880.75   \n",
       "\n",
       "    energy_price_index_(usd/kwh)  \n",
       "0                           0.12  \n",
       "5                           0.35  \n",
       "17                          0.47  \n",
       "29                          0.18  \n",
       "34                          0.13  "
      ]
     },
     "execution_count": 56,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "energy.head()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
